name: las-bambas-analysis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - jupyterlab
  - fiona=1.10.1
  - gdal=3.12.*
  - geopandas=1.1.*
  - rasterio=1.4.*
  - shapely=2.1.*
  - pip:
      - numpy==2.4.3
      - pandas==2.3.3
      - scipy==1.17.1
      - scikit-learn==1.8.0
      - matplotlib==3.10.8
      - seaborn==0.13.2
      - contextily==1.7.0
      - earthengine-api==1.7.18
      - folium==0.20.0
      - geemap==0.37.2
      - mlxtend==0.24.0
      - requests==2.32.5
      - -e .
